'use client';

import { useState, useEffect } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import * as z from 'zod';
import { useCollection, useFirestore, useUser, useMemoFirebase } from '@/firebase';
import { collection, query, where } from 'firebase/firestore';
import type { TestCase, Project } from '@/lib/types';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Checkbox } from '@/components/ui/checkbox';
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';
import { useToast } from '@/hooks/use-toast';
import { generateAutomationScript, type AutomationScriptInput } from '@/ai/ai-automation-script-generation';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Bot, Copy, ArrowLeft } from 'lucide-react';
import { useRouter } from 'next/navigation';

const formSchema = z.object({
  projectId: z.string().min(1, { message: 'Please select a project.' }),
  testCaseIds: z.array(z.string()).min(1, { message: 'Please select at least one test case.' }),
  automationFramework: z.enum(['Playwright', 'Cypress', 'Selenium']),
});

export default function AiScriptGeneratorPage() {
  const router = useRouter();
  const { user } = useUser();
  const firestore = useFirestore();
  const { toast } = useToast();
  const [generatedScript, setGeneratedScript] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [selectedProjectId, setSelectedProjectId] = useState('');

  const projectsQuery = useMemoFirebase(() => {
    if (!user || !firestore) return null;
    return collection(firestore, `users/${user.uid}/projects`);
  }, [user, firestore]);

  const testCasesQuery = useMemoFirebase(() => {
    if (!user || !firestore || !selectedProjectId) return null;
    return collection(firestore, `users/${user.uid}/projects/${selectedProjectId}/testCases`);
  }, [user, firestore, selectedProjectId]);

  const { data: projects, isLoading: areProjectsLoading } = useCollection<Project>(projectsQuery);
  const { data: testCases, isLoading: areTestCasesLoading } = useCollection<TestCase>(testCasesQuery);

  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      projectId: '',
      testCaseIds: [],
      automationFramework: 'Playwright',
    },
  });

  useEffect(() => {
    const subscription = form.watch((value, { name }) => {
      if (name === 'projectId') {
        setSelectedProjectId(value.projectId || '');
        form.reset({ ...value, testCaseIds: [] });
      }
    })
    return () => subscription.unsubscribe()
  }, [form]);

  async function onSubmit(values: z.infer<typeof formSchema>) {
    if (!testCases) return;

    setIsGenerating(true);
    setGeneratedScript('');
    
    const selectedTestCases = testCases.filter(tc => values.testCaseIds.includes(tc.id));
    const inputForAI: AutomationScriptInput = {
      testCases: selectedTestCases.map(tc => ({
        testCaseTitle: tc.title,
        testSteps: tc.testSteps,
        expectedResult: tc.expectedResult,
      })),
      automationFramework: values.automationFramework,
    };

    try {
      const result = await generateAutomationScript(inputForAI);
      setGeneratedScript(result.script);
      toast({
        title: 'Script Generated!',
        description: 'The automation script has been successfully generated by AI.',
      });
    } catch (error) {
      console.error("Error generating script:", error);
      toast({
        variant: 'destructive',
        title: 'Generation Failed',
        description: 'There was a problem generating the script.',
      });
    } finally {
      setIsGenerating(false);
    }
  }

  const copyToClipboard = () => {
    navigator.clipboard.writeText(generatedScript);
    toast({
      title: 'Copied to Clipboard!',
    });
  };

  return (
    <div className='grid gap-6'>
      <div className='flex justify-start'>
          <Button variant="outline" onClick={() => router.back()}>
              <ArrowLeft className="mr-2 h-4 w-4" />
              Back
          </Button>
       </div>
        <div className="grid gap-8 md:grid-cols-2">
      <Card>
        <CardHeader>
          <CardTitle>AI Automation Script Generator</CardTitle>
          <CardDescription>Select a project, test cases, and a framework to generate an automation script.</CardDescription>
        </CardHeader>
        <CardContent>
          <Form {...form}>
            <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
              <FormField
                control={form.control}
                name="projectId"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Project</FormLabel>
                    <Select onValueChange={field.onChange} defaultValue={field.value} disabled={areProjectsLoading}>
                      <FormControl>
                        <SelectTrigger>
                          <SelectValue placeholder="Select a project" />
                        </SelectTrigger>
                      </FormControl>
                      <SelectContent>
                        {projects?.map(p => <SelectItem key={p.id} value={p.id}>{p.name}</SelectItem>)}
                      </SelectContent>
                    </Select>
                    <FormMessage />
                  </FormItem>
                )}
              />
              
              <FormField
                control={form.control}
                name="testCaseIds"
                render={() => (
                  <FormItem>
                    <FormLabel>Test Cases</FormLabel>
                    <Card className='p-4'>
                      <ScrollArea className="h-72">
                      {areTestCasesLoading ? (
                        <p className='text-muted-foreground text-sm'>Loading test cases...</p>
                      ) : !selectedProjectId ? (
                        <p className='text-muted-foreground text-sm'>Please select a project first.</p>
                      ): (
                        testCases?.map((item) => (
                          <FormField
                            key={item.id}
                            control={form.control}
                            name="testCaseIds"
                            render={({ field }) => {
                              return (
                                <FormItem
                                  key={item.id}
                                  className="flex flex-row items-start space-x-3 space-y-0 py-2"
                                >
                                  <FormControl>
                                    <Checkbox
                                      checked={field.value?.includes(item.id)}
                                      onCheckedChange={(checked) => {
                                        return checked
                                          ? field.onChange([...(field.value || []), item.id])
                                          : field.onChange(
                                              field.value?.filter(
                                                (value) => value !== item.id
                                              )
                                            )
                                      }}
                                    />
                                  </FormControl>
                                  <FormLabel className="font-normal w-full cursor-pointer">
                                    {item.title}
                                  </FormLabel>
                                </FormItem>
                              )
                            }}
                          />
                        ))
                      )}
                      </ScrollArea>
                    </Card>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="automationFramework"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Automation Framework</FormLabel>
                    <Select onValueChange={field.onChange} defaultValue={field.value}>
                      <FormControl>
                        <SelectTrigger>
                          <SelectValue placeholder="Select a framework" />
                        </SelectTrigger>
                      </FormControl>
                      <SelectContent>
                        <SelectItem value="Playwright">Playwright</SelectItem>
                        <SelectItem value="Cypress">Cypress</SelectItem>
                        <SelectItem value="Selenium">Selenium</SelectItem>
                      </SelectContent>
                    </Select>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <Button type="submit" disabled={isGenerating} className="w-full">
                <Bot className="mr-2 h-4 w-4" />
                {isGenerating ? 'Generating...' : 'Generate Script'}
              </Button>
            </form>
          </Form>
        </CardContent>
      </Card>

      <Card>
        <CardHeader className="flex flex-row items-center justify-between">
          <div>
            <CardTitle>Generated Script</CardTitle>
            <CardDescription>Review the AI-generated script below.</CardDescription>
          </div>
          {generatedScript && (
            <Button variant="outline" size="icon" onClick={copyToClipboard}>
              <Copy className="h-4 w-4" />
              <span className='sr-only'>Copy Script</span>
            </Button>
          )}
        </CardHeader>
        <CardContent>
          {isGenerating ? (
            <div className="flex justify-center items-center h-72">
              <p className="text-muted-foreground">Generating your script...</p>
            </div>
          ) : (
            <ScrollArea className="h-96 rounded-md border bg-muted/50 p-4 font-mono text-sm">
                <pre>
                    <code>
                        {generatedScript || 'Your generated script will appear here...'}
                    </code>
                </pre>
            </ScrollArea>
          )}
        </CardContent>
      </Card>
    </div>

    </div>
  );
}
